---

- name: Create /etc/X11/xorg.conf.d directory if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    mode: 0755
  with_items:
    - /etc/X11/xorg.conf.d

- name: Tweak touchpad
  import_tasks: touchpad.yml

- name: Tweak intel_backlight
  import_tasks: intel_backlight.yml

- name: Suspend when lid closed
  lineinfile:
    path: /etc/systemd/logind.conf
    backup: yes
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - { regexp: "^#HandlePowerKey=",    line: "HandlePowerKey=hibernate"}
    - { regexp: "^#HandleLidSwitch=",   line: "HandleLidSwitch=suspend"}
    - { regexp: "^#HoldoffTimeoutSec=", line: "HoldoffTimeoutSec=30s"}
    - { regexp: "^#IdleAction=",        line: "IdleAction=suspend"}
    - { regexp: "^#IdleActionSec=",     line: "IdleActionSec=10min"}

- name: Lock screen before suspending
  template:
    src:   etc/systemd/system/lock-screen-before-suspending.service
    dest:  /etc/systemd/system/lock-screen-before-suspending.service
    owner: root
    group: root
    mode:  0644

- name: Enable lock-screen-before-suspending
  command: 'systemctl enable lock-screen-before-suspending.service'
  args:
    chdir: /etc/systemd/system

- name: Check if swappiness already set
  shell: grep "^vm.swappiness" /etc/sysctl.conf; exit 0
  register: test_grep_swappiness

- name: Change swappiness to 0
  lineinfile:
    path: /etc/sysctl.conf
    line: "vm.swappiness=0"
  when: test_grep_swappiness.stdout != ""
