- name: Lock screen before suspending
  template:
    src: etc/systemd/system/lock-screen-before-suspending.service
    dest: /etc/systemd/system/lock-screen-before-suspending.service
    owner: root
    group: root
    mode: 0644

- name: Enable lock-screen-before-suspending
  command: "systemctl enable lock-screen-before-suspending.service"
  args:
    chdir: /etc/systemd/system

- name: Power tuning
  template:
    src: etc/systemd/system/powertop.service
    dest: /etc/systemd/system/powertop.service
    owner: root
    group: root
    mode: 0644

- name: Enable powertop.service
  command: "systemctl enable powertop.service"
  args:
    chdir: /etc/systemd/system
