---

- name: Create /etc/X11/xorg.conf.d/70-synaptics.conf file if it is not exist
  file:
    path: "{{ item }}"
    state: touch
    owner: root
    mode: 0755
  with_items:
    - /etc/X11/xorg.conf.d/70-synaptics.conf

- name: Tweak touchpad
  blockinfile:
    path: /etc/X11/xorg.conf.d/70-synaptics.conf
    backup: yes
    block: |
      Section "InputClass"
              Identifier "touchpad"
              MatchDriver "synaptics"
              MatchIsTouchpad "on"
                  Option "HorizEdgeScroll" "on"
                  Option "HorizScrollDelta" "-114"
                  Option "HorizTwoFingerScroll" "on"
                  Option "MaxTapTime" "125"
                  Option "PalmDetect" "1"
                  Option "PalmMinWidth" "8"
                  Option "PalmMinZ" "100"
                  Option "TapButton1" "1"
                  Option "TapButton2" "3"
                  Option "TapButton3" "2"
                  Option "VertEdgeScroll" "on"
                  Option "VertScrollDelta" "-114"
                  Option "VertTwoFingerScroll" "on"
      EndSection
