---

- name: Add nix-store entry to crontab
  cron:
    name: "nix-store --optimise"
    minute: "0"
    hour: "10"
    weekday: "1"
    job: "/home/bangn/.nix-profile/bin/nix-store --optimise"
  tags: cron

- name: Add nix-collect-garbage to crontab
  cron:
    name: "nix-collect-garbage --delete-old"
    minute: "0"
    hour: "11"
    weekday: "1"
    job: "/home/bangn/.nix-profile/bin/nix-collect-garbage --delete-old"
  tags: cron

- name: Update Steven Black hosts file
  cron:
    name: "Update Steven Black hosts"
    minute: "0"
    hour: "12"
    weekday: "1"
    job: "/home/bangn/dotfiles/tools/bin/steven-black-host"
  tags: cron

- name: Let exim4 send to personal account
  become: true
  become_user: root
  template:
    src:   etc/exim4/update-exim4.conf.conf
    dest:  /etc/exim4/update-exim4.conf.conf
    owner: root
    group: root
    mode:  0644
  tags: exim4

- name: Update exim4 passwd.client
  become: true
  become_user: root
  template:
    src:   etc/exim4/passwd.client
    dest:  /etc/exim4/passwd.client
    owner: root
    group: root
    mode:  0644
  tags: exim4

- name: Create exim4.conf.localmacros
  become: true
  become_user: root
  template:
    src:   etc/exim4/exim4.conf.localmacros
    dest:  /etc/exim4/exim4.conf.localmacros
    owner: root
    group: root
  tags: exim4

- name: Add personal email to /etc/aliases
  become: true
  become_user: root
  blockinfile:
    path: /etc/aliases
    block: |
      bangn: thebangnguyen@gmail.com
  tags: exim4

- name: Create user directory
  file:
    path: "{{item.path}}"
    state: directory
    owner: bangn
  with_items:
    - {path: "/home/bangn/oss"}
  tags:
    - directory

- name: Add backup group
  become: true
  become_user: root
  group:
    name: backup
    state: present
  tags:
    - backup

- name: Add bangn to backup
  become: true
  become_user: root
  user:
    name: bangn
    group: backup
    append: yes
  tags:
    - backup

- name: Create backup directory
  become: true
  become_user: root
  file:
    path: "{{item.path}}"
    state: directory
    group: backup
    mode: 0774
  with_items:
    - {path: "/media/backup"}
  tags:
    - backup

- name: Add hard drive mount point to fstab
  become: true
  become_user: root
  lineinfile:
    path: /etc/fstab
    line: "UUID=2521b73d-0f67-4c6f-8423-4a44956c0c89\t/media/backup\text4\tdefaults\t0\t2"
  tags:
    - backup
