---

- name: Add nix-store entry to crontab
  cron:
    name: "nix-store --optimise"
    minute: "0"
    hour: "10"
    weekday: "1"
    job: "/home/bangn/.nix-profile/bin/nix-store --optimise"
  tags: cron

- name: Add nix-collect-garbage to crontab
  cron:
    name: "nix-collect-garbage --delete-old"
    minute: "0"
    hour: "11"
    weekday: "1"
    job: "/home/bangn/.nix-profile/bin/nix-collect-garbage --delete-old"
  tags: cron

- name: Update Steven Black hosts file
  cron:
    name: "Update Steven Black hosts"
    minute: "0"
    hour: "12"
    weekday: "1"
    job: "/home/bangn/dotfiles/tools/bin/steven-black-host"
  tags: cron

- name: Copy exim4 config files to /etc/exim4
  become: true
  become_user: root
  copy:
    force: true
    src:   ./exim4/
    dest:  /etc/exim4/
    owner: root
    group: root
  tags: exim4

- name: Add personal email to /etc/aliases
  become: true
  become_user: root
  blockinfile:
    path: /etc/aliases
    block: |
      bangn: thebangnguyen@gmail.com
  tags: exim4

- name: Create user directory
  file:
    path: "{{item.path}}"
    state: directory
    owner: bangn
  with_items:
    - {path: "/home/bangn/oss"}
  tags:
    - directory

- name: Add backup group
  become: true
  become_user: root
  group:
    name: backup
    state: present
  tags:
    - backup

- name: Add bangn to backup
  become: true
  become_user: root
  user:
    name: bangn
    group: backup
    append: yes
  tags:
    - backup

- name: Create backup directory
  become: true
  become_user: root
  file:
    path: "{{item.path}}"
    state: directory
    group: backup
    mode: 0774
  with_items:
    - {path: "/media/backup"}
  tags:
    - backup

- name: Add hard drive mount point to fstab
  become: true
  become_user: root
  lineinfile:
    path: /etc/fstab
    line: "UUID=77f75973-ac5a-4fe0-a1d8-afff947fa647\t/media/backup\text4\tnofail\t0\t2"
  tags:
    - backup

- name: Preserve LD_LIBRARY_PATH
  become: true
  become_user: root
  template:
    src:   etc/X11/Xsession.d/90preserve_ld_library_path
    dest:  /etc/X11/Xsession.d/90preserve_ld_library_path
    owner: root
    group: root
    mode:  0644
  tags:
    - systems

- name: Disable sof audio driver and fall back to intel
  become: true
  become_user: root
  replace:
    path: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX_DEFAULT'
    replace: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash snd_hda_intel.dmic_detect=0"'
  tags:
    - systems

- name: Update grub after replace sof audio driver with intel
  become: true
  become_user: root
  command: 'update-grub'
