---
- name: Add nix-store entry to crontab
  cron:
    name: "nix-store --optimise"
    minute: "0"
    hour: "10"
    weekday: "1"
    job: "/home/bangn/.nix-profile/bin/nix-store --optimise"
  tags: cron

- name: Add nix-collect-garbage to crontab
  cron:
    name: "nix-collect-garbage --delete-old"
    minute: "0"
    hour: "11"
    weekday: "1"
    job: "/home/bangn/.nix-profile/bin/nix-collect-garbage --delete-old"
  tags: cron

- name: Update Steven Black hosts file
  cron:
    name: "Update Steven Black hosts"
    minute: "0"
    hour: "12"
    weekday: "1"
    job: "/home/bangn/dotfiles/tools/bin/steven-black-host"
  tags: cron

- name: Copy exim4 config files to /etc/exim4
  become: true
  become_user: root
  copy:
    force: true
    src: ./exim4/
    dest: /etc/exim4/
    owner: root
    group: root
    mode: preserve
  tags: exim4

- name: Add personal email to /etc/aliases
  become: true
  become_user: root
  blockinfile:
    path: /etc/aliases
    block: |
      bangn: thebangnguyen@gmail.com
  tags: exim4

- name: Create user directory
  file:
    path: "{{item.path}}"
    state: directory
    owner: bangn
  with_items:
    - { path: "/home/bangn/oss" }
  tags:
    - directory

- name: Preserve LD_LIBRARY_PATH
  become: true
  become_user: root
  template:
    src: etc/X11/Xsession.d/90preserve_ld_library_path
    dest: /etc/X11/Xsession.d/90preserve_ld_library_path
    owner: root
    group: root
    mode: 0644
  tags:
    - systems

- name: Comment out specific line in ssh_config
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/ssh/ssh_config
    regexp: '^\s*GSSAPIAuthentication yes' # The line you want to comment out
    line: '# GSSAPIAuthentication yes'  # The commented line
    state: present  # Ensure the line is present in its commented form
  tags:
    - systems
