---

- name: Add nix-store entry to crontab
  cron:
    name: "nix-store --optimise"
    minute: "0"
    hour: "10"
    weekday: "1"
    job: "/home/bangn/.nix-profile/bin/nix-store --optimise"
  tags: cron

- name: Add nix-collect-garbage to crontab
  cron:
    name: "nix-collect-garbage --delete-old"
    minute: "0"
    hour: "11"
    weekday: "1"
    job: "/home/bangn/.nix-profile/bin/nix-collect-garbage --delete-old"
  tags: cron

- name: Update Steven Black hosts file
  cron:
    name: "Update Steven Black hosts"
    minute: "0"
    hour: "12"
    weekday: "1"
    job: "/home/bangn/dotfiles/tools/bin/steven-black-host"
  tags: cron

- name: Let exim4 send to personal account
  become: true
  become_user: root
  template:
    src:   etc/exim4/update-exim4.conf.conf
    dest:  /etc/exim4/update-exim4.conf.conf
    owner: root
    group: root
    mode:  0640
  tags: exim4

- name: Update exim4 passwd.client
  become: true
  become_user: root
  template:
    src:   etc/exim4/passwd.client
    dest:  /etc/exim4/passwd.client
    owner: root
    group: root
    mode:  0644
  tags: exim4

- name: Create exim4.conf.localmacros
  become: true
  become_user: root
  template:
    src:   etc/exim4/exim4.conf.localmacros
    dest:  /etc/exim4/exim4.conf.localmacros
    owner: root
    group: root
  tags: exim4

- name: Add personal email to /etc/aliases
  become: true
  become_user: root
  blockinfile:
    path: /etc/aliases
    block: |
      bangn: thebangnguyen@gmail.com
  tags: exim4

- name: Create directory
  file:
    path: "{{item.path}}"
    state: directory
    owner: bangn
  with_items:
    - {path: "/home/bangn/oss"}
  tags:
    - directory
