---

- name: Add nix-store entry to crontab
  cron:
    name: "nix-store --optimise"
    minute: "0"
    hour: "10"
    weekday: "1"
    job: "/home/bangn/.nix-profile/bin/nix-store --optimise"

- name: Add nix-collect-garbage to crontab
  cron:
    name: "nix-collect-garbage --delete-old"
    minute: "0"
    hour: "11"
    weekday: "1"
    job: "/home/bangn/.nix-profile/bin/nix-collect-garbage --delete-old"

- name: Let exim4 send to personal account
  become: true
  become_user: root
  template:
    src:   etc/exim4/update-exim4.conf.conf
    dest:  /etc/exim4/update-exim4.conf.conf
    owner: root
    group: root
    mode:  0640

- name: Update exim4 passwd.client
  become: true
  become_user: root
  template:
    src:   etc/exim4/passwd.client
    dest:  /etc/exim4/passwd.client
    owner: root
    group: root
    mode:  0640

- name: Create exim4.conf.localmacros
  become: true
  become_user: root
  template:
    src:   etc/exim4/exim4.conf.localmacros
    dest:  /etc/exim4/exim4.conf.localmacros
    owner: root
    group: root

# Got ERROR for this task. Have not figured out yet
# The file needs to be copied manually
# - name: Create exim4.conf.template
#   become: true
#   become_user: root
#   template:
#     src:   etc/exim4/exim4.conf.template
#     dest:  /etc/exim4/exim4.conf.template
#     owner: root
#     group: root

- name: Add personal email to /etc/aliases
  become: true
  become_user: root
  blockinfile:
    path: /etc/aliases
    block: |
      bangn: thebangnguyen@gmail.com
