#! /bin/bash

if [ ! -x "$(command -v ansible)" ]; then
  sudo apt update
  sudo apt install -y python3-pip
  pip3 install ansible
fi

export PATH="~/.local/bin:$PATH"
ansible-playbook -i inventories/localhost playbook.yml -K
