#! /bin/bash

if [ ! -x "$(command -v ansible)" ]; then
	sudo echo deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main | sudo tee -a /etc/apt/sources.list
	sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
	sudo apt-get update
	sudo apt-get install ansible -y
fi

ansible-galaxy install -r requirements.yml
ansible-playbook -i inventories/localhost playbook.yml -K
