---

- hosts: "localhost"
  roles:
    - role: apt
      become: true
      become_user: root

    - role: users

    - role: packages

    - role: dotfiles

    - role: thinkpad-tweak
      become: yes
      become_method: sudo

    - role: cimon-io.asdf
      asdf_user: bangn
