---

- hosts: "localhost"
  roles:
    - role: apt
      become: true
      become_user: root
      tags:
        - apt

    - role: users
      tags:
        - users

    - role: thinkpad-tweak
      become: yes
      become_method: sudo
      tags:
        - thinkpad

    - role: packages
      tags:
        - packages

    - role: systems
      tags:
        - systems

    - role: lxc
      become: true
      become_user: root
      tags:
        - lxc

    - role: dotfiles
      tags:
        - dotfiles

    - role: dns
      tags:
        - dns
