---

- hosts: "localhost"
  roles:
    - role: users

    - role: packages

    - role: dotfiles

    - role: thinkpad-tweak
      become: yes
      become_method: sudo

    - role: cimon-io.asdf
      asdf_user: bangn
      asdf_plugins:
        - name: "ruby"
          versions:
            - 2.6.0
          global: 2.6.0
