---
- hosts: all
  become: yes
  become_user: root
  roles:
    - role: security
      tags:
        - security
    - role: exim4
      tags:
        - exim4

- hosts: localhost
  roles:
    - role: apt
      become: yes
      become_user: root
      tags:
        - apt

    - role: users
      tags:
        - users

    - role: thinkpad-tweak
      become: yes
      become_method: sudo
      tags:
        - thinkpad

    - role: packages
      tags:
        - packages

    - role: systems
      tags:
        - systems

    - role: dotfiles
      tags:
        - dotfiles

    - role: caddy
      become: yes
      become_method: sudo
      tags:
        - caddy

    - role: grafana
      become: yes
      become_method: sudo
      tags:
        - grafana

    - role: dns
      become: yes
      become_method: sudo
      tags:
        - dns
