---

- hosts: "localhost"
  roles:
    - role: packages

    - role: users

    - role: dotfiles

    - role: cimon-io.asdf
      asdf_user: bangn
      asdf_plugins:
        - name: "python"
          versions:
            - 3.6.4
          global: 3.6.4
        - name: "ruby"
          versions:
            - 2.5.0
          global: 2.5.0
