---
# Variables that an end user should likely never modify.

tailscale_package: tailscale
tailscale_service: tailscaled

tailscale_debian_distro:
  pop!_os: ubuntu
  ubuntu: ubuntu
  debian: debian
  osmc: debian

tailscale_apt_keyring_path: /usr/share/keyrings/tailscale-archive-keyring.gpg

tailscale_apt_deb: deb [signed-by={{ tailscale_apt_keyring_path }}] https://pkgs.tailscale.com/{{ release_stability | lower }}/{{ tailscale_debian_distro[ansible_distribution | lower] }} {{ ansible_distribution_release | lower }} main

tailscale_apt_signkey: https://pkgs.tailscale.com/{{ release_stability | lower }}/{{ tailscale_debian_distro[ansible_distribution | lower] }}/{{ ansible_distribution_release | lower }}.noarmor.gpg

tailscale_original_distribution_major_version: "{{ ansible_distribution_major_version }}"
