---

# Debian buster wifi
- name: Add debian buster non-free contrib
  apt_repository:
    repo: deb http://httpredir.debian.org/debian/ buster main contrib non-free
    state: present

# Google Chrome
- name: Add google-chrome key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: Add google-chrome repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
