---

# Debian buster wifi
- name: Add debian buster non-free contrib
  apt_repository:
    repo: deb http://httpredir.debian.org/debian/ buster main contrib non-free
    state: present

# Google Chrome
- name: Add google-chrome repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present

# VSCode installation
- name: Install curl
  apt:
    name: curl
    state: latest
    update_cache: yes

- name: Add Microsoft PPA Repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
