---

# Debian buster contrib and non-free
- name: Add debian buster non-free contrib
  apt_repository:
    repo: deb http://deb.debian.org/debian/ buster contrib non-free
    state: present

# Debian buster security update apt repo
- name: Add debian buster security update apt repo
  apt_repository:
    repo: deb http://security.debian.org/ buster/updates contrib non-free
    state: present

# Debian buster stable update apt repo
- name: Add debian buster security update apt repo
  apt_repository:
    repo: deb http://ftp.debian.org/debian buster-updates contrib non-free
    state: present

# Google Chrome
- name: Add google-chrome key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: Add google-chrome repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
