---
- name: Add debian testing non-free contrib
  apt_repository:
    repo: deb http://deb.debian.org/debian/ testing contrib non-free
    state: present

- name: Add debian testing security update apt repo
  apt_repository:
    repo: deb http://security.debian.org/ testing/updates contrib non-free
    state: present

- name: Add debian testing stable update apt repo
  apt_repository:
    repo: deb http://ftp.debian.org/debian testing-updates contrib non-free
    state: present

- name: Add debian testing backport apt repo
  apt_repository:
    repo: deb http://deb.debian.org/debian testing-backports main contrib non-free
    state: present
