---

- name: Add debian buster non-free contrib
  apt_repository:
    repo: deb http://deb.debian.org/debian/ buster contrib non-free
    state: present

- name: Add debian buster security update apt repo
  apt_repository:
    repo: deb http://security.debian.org/ buster/updates contrib non-free
    state: present

- name: Add debian buster stable update apt repo
  apt_repository:
    repo: deb http://ftp.debian.org/debian buster-updates contrib non-free
    state: present

- name: Add debian buster backport apt repo
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main contrib non-free
    state: present
