---

## VSCode installation
- name: Download Microsoft GPG
  command: sh -c 'curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg'
- name: Entrust Microsoft GPG
  command: mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
- name: Add Microsoft PPA
  command: sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
- name: Install VSCode
  apt:
    name: code
    state: latest
    update_cache: yes
## End VSCode installation

# stack for Haskell development
- name: Install Stack for Haskell development
  become: yes
  become_user: bangn
  command: zsh -c 'if ! command -v stack; then curl -sSL https://get.haskellstack.org/ | sh; fi'
# Endstack for Haskell development

- name: Install vim-anywhere
  become: yes
  become_user: bangn
  command: bash -c 'curl -fsSL https://raw.github.com/cknadler/vim-anywhere/master/install | bash'

- name: Install nix packages manager
  become: yes
  become_user: bangn
  command: bash -c 'curl https://nixos.org/nix/install | sh'
