---

- name: Prepare for installing nix
  become: yes
  become_user: root
  file:
    path: /nix
    state: directory
    owner: bangn
    group: bangn
    mode: '0755'

- name: Allow unprivileged userns clone
  become: true
  become_user: root
  command: sysctl kernel.unprivileged_userns_clone=1

- name: Install nix packages manager
  command: bash -c 'curl https://nixos.org/nix/install | sh'

- name: Install asdf-vm
  command: bash -c 'git clone https://github.com/asdf-vm/asdf.git ~/.asdf'
