---

# stack for Haskell development
- name: Install Stack for Haskell development
  command: zsh -c 'if ! command -v stack; then curl -sSL https://get.haskellstack.org/ | sh; fi'
# Endstack for Haskell development

- name: Install vim-anywhere
  command: bash -c 'curl -fsSL https://raw.github.com/cknadler/vim-anywhere/master/install | bash'

- name: Install nix packages manager
  command: bash -c 'curl https://nixos.org/nix/install | sh'
