---

## VSCode installation
- name: Download Microsoft GPG
  command: sh -c 'curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg'
- name: Entrust Microsoft GPG
  command: mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
- name: Add Microsoft PPA
  command: sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
- name: Install VSCode
  apt:
    name: code
    state: latest
    update_cache: yes
## End VSCode installation

## stack for Haskell development
#- name: Install Stack for Haskell development
#  command: sh -c 'curl -sSL https://get.haskellstack.org/ | sh'
## Endstack for Haskell development
