---

# Ubuntu/Debian packages
- name: Install deb packages
  apt:
    name: "{{item.name}}"
    state: "{{item.state}}"
    update_cache: yes
  with_items:
    - { name: arandr                       , state: present }
    - { name: autojump                     , state: present }
    - { name: cabal-install                , state: present }
    - { name: clipit                       , state: present }
    - { name: ctags                        , state: present }
    - { name: curl                         , state: present }
    - { name: exfat-fuse                   , state: present }
    - { name: exfat-utils                  , state: present }
    - { name: fbreader                     , state: present }
    - { name: fcitx                        , state: present }
    - { name: feh                          , state: present }
    - { name: git                          , state: present }
    - { name: htop                         , state: present }
    - { name: i3                           , state: present }
    - { name: imagemagick                  , state: present }
    - { name: jq                           , state: present }
    - { name: libssl1.0-dev                , state: present } # For installing ruby < 2.4
    - { name: ncdu                         , state: present }
    - { name: neovim                       , state: present }
    - { name: pandoc                       , state: present }
    - { name: scrot                        , state: present }
    - { name: shellcheck                   , state: present }
    - { name: silversearcher-ag            , state: present }
    - { name: stow                         , state: present }
    - { name: tmux                         , state: present }
    - { name: tree                         , state: present }
    - { name: vagrant                      , state: present }
    - { name: vim-gnome                    , state: present }
    - { name: virtualbox                   , state: present }
    - { name: xautolock                    , state: latest  }
    - { name: xbacklight                   , state: latest  }
    - { name: xclip                        , state: present }
    - { name: xserver-xorg-input-synaptics , state: latest  }
    - { name: xserver-xorg-video-intel     , state: latest  }
    - { name: yamllint                     , state: present }
    - { name: zsh                          , state: present }

- name: Install slack using snap
  command: snap install slack --classic
  become: yes
  become_method: sudo

- name: Add google-chrome key
  command: bash -c "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -"

- name: Set google-chrome repository
  command: bash -c "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list"

- name: Install google-chrome
  become: yes
  become_method: sudo
  apt:
    name: google-chrome-stable
    state: present
    update_cache: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
