---
# Deb packages
- name: Install deb packages
  apt:
    name: "{{item.name}}"
    state: "{{item.state}}"
    update_cache: yes
  with_items:
    - { name: acpi-call-dkms, state: present }
    - { name: apticron, state: latest }
    - { name: arandr, state: present }
    - { name: atril, state: absent }
    - { name: blueman, state: present }
    - { name: borgbackup, state: latest }
    - { name: ca-certificates, state: latest }
    - { name: cups, state: present }
    - { name: cups-pdf, state: present }
    - { name: dnsmasq, state: absent }
    - { name: dnsutils, state: present }
    - { name: exfat-fuse, state: present }
    - { name: exim4, state: latest }
    - { name: fcitx, state: present }
    - { name: firmware-iwlwifi, state: latest }
    - { name: firmware-linux, state: latest }
    - { name: firmware-sof-signed, state: latest }
    - { name: fonts-font-awesome, state: present }
    - { name: fonts-hack, state: present }
    - { name: fonts-hack-ttf, state: present }
    - { name: fwupd, state: present }
    - { name: git, state: present } # Use git from nix
    - { name: i3, state: latest }
    - { name: i3blocks, state: latest }
    - { name: ldnsutils, state: present }
    - { name: libnss3-tools, state: latest }
    - { name: libpq-dev, state: present } # For installing pg gem
    - { name: libreadline-dev, state: present }
    - { name: libssl-dev, state: latest }
    - { name: libyaml-dev, state: latest }
    - { name: neovim, state: absent }
    - { name: openconnect, state: present }
    - { name: openssl, state: latest }
    - { name: prometheus, state: latest }
    - { name: prometheus-node-exporter, state: latest }
    - { name: python3-dev, state: latest }
    - { name: python3-pip, state: latest }
    - { name: python3-pynvim, state: latest }
    - { name: python3-venv, state: latest }
    - { name: rkhunter, state: latest }
    - { name: rofi, state: present }
    - { name: rsync, state: latest }
    - { name: scrot, state: present }
    - { name: ssh-askpass, state: latest }
    - { name: ssh-askpass-gnome, state: latest }
    - { name: texlive-fonts-extra, state: latest }
    - { name: texlive-fonts-recommended, state: latest }
    - { name: texlive-latex-base, state: latest }
    - { name: texlive-latex-extra, state: latest }
    - { name: tlp, state: present }
    - { name: tp-smapi-dkms, state: present }
    - { name: unattended-upgrades, state: latest }
    - { name: xautolock, state: latest }
    - { name: xbacklight, state: latest }
    - { name: xdotool, state: latest }
    - { name: xfce4-clipman, state: latest }
    - { name: xfce4-clipman-plugin, state: latest }
    - { name: xserver-xorg-input-synaptics, state: latest }
    - { name: xserver-xorg-video-intel, state: latest }
    - { name: zathura, state: present }
    - { name: zlib1g-dev, state: present }
    - { name: zsh, state: latest }

    # Alacritty
    - { name: cmake, state: latest }
    - { name: libfontconfig1-dev, state: latest }
    - { name: libfreetype6-dev, state: latest }
    - { name: libxcb-xfixes0-dev, state: latest }
    - { name: libxkbcommon-dev, state: latest }
    - { name: pkg-config, state: latest }

    # ghcup
    - { name: libffi-dev, state: latest }
    - { name: libgmp-dev, state: latest }
    - { name: libgmp10, state: latest }
    - { name: libncurses-dev, state: latest }
    - { name: libncurses5, state: latest }
    - { name: libtinfo5, state: latest }

    # pact
    - { name: libsqlite3-dev, state: latest }

    # neovim
    - { name: automake, state: latest }
    - { name: autoconf, state: latest }
    - { name: gettext, state: latest }
    - { name: libtool, state: latest }
    - { name: libtool-bin, state: latest }
    - { name: ninja-build, state: latest }

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
