---

# Ubuntu/Debian packages
- name: Install deb packages
  apt:
    name: "{{item.name}}"
    state: "{{item.state}}"
    update_cache: yes
  with_items:
    - { name: arandr                       , state: present }
    - { name: autojump                     , state: present }
    - { name: curl                         , state: present }
    - { name: git                          , state: present }
    - { name: jq                           , state: present }
    - { name: neovim                       , state: present }
    - { name: shellcheck                   , state: present }
    - { name: silversearcher-ag            , state: present }
    - { name: stow                         , state: present }
    - { name: tmux                         , state: present }
    - { name: tree                         , state: present }
    - { name: vim-gnome                    , state: present }
    - { name: xclip                        , state: present }
    - { name: yamllint                     , state: present }
    - { name: zsh                          , state: present }

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
