---

# Deb packages
- name: Install deb packages
  apt:
    name: "{{item.name}}"
    state: "{{item.state}}"
    update_cache: yes
  with_items:
    - {name: acpi-call-dkms, state: present}
    - {name: apticron, state: latest}
    - {name: arandr, state: present}
    - {name: autojump, state: present}
    - {name: borgbackup, state: latest}
    - {name: ctags, state: latest}
    - {name: cups, state: present}
    - {name: cups-pdf, state: present}
    - {name: curl, state: present}
    - {name: direnv, state: latest}
    - {name: dnsmasq, state: present}
    - {name: dnsutils, state: present}
    - {name: evince, state: present}
    - {name: exfat-fuse, state: present}
    - {name: exfat-utils, state: present}
    - {name: fbreader, state: present}
    - {name: fcitx, state: present}
    - {name: feh, state: present}
    - {name: firmware-iwlwifi, state: latest}
    - {name: fonts-hack, state: present}
    - {name: fonts-hack-ttf, state: present}
    - {name: git, state: latest}
    - {name: google-chrome-stable, state: latest}
    - {name: google-cloud-sdk, state: present}
    - {name: graphviz, state: present}
    - {name: htop, state: present}
    - {name: i3, state: latest}
    - {name: imagemagick, state: present}
    - {name: jq, state: present}
    - {name: kdiff3, state: latest}
    - {name: ldnsutils, state: present}
    - {name: libpq-dev, state: present}   # For installing pg gem
    - {name: ncdu, state: present}
    - {name: neovim, state: latest}
    - {name: openconnect, state: present}
    - {name: pandoc, state: present}
    - {name: python3-dev, state: latest}
    - {name: python3-neovim, state: latest}
    - {name: python3-pip, state: latest}
    - {name: rkhunter, state: latest}
    - {name: rsync, state: latest}
    - {name: scrot, state: present}
    - {name: shellcheck, state: latest}
    - {name: silversearcher-ag, state: latest}
    - {name: stow, state: present}
    - {name: texlive-fonts-extra, state: latest}
    - {name: texlive-fonts-recommended, state: latest}
    - {name: texlive-latex-base, state: latest}
    - {name: texlive-latex-extra, state: latest}
    - {name: tlp, state: present}
    - {name: tmux, state: latest}
    - {name: tp-smapi-dkms, state: present}
    - {name: tree, state: present}
    - {name: unattended-upgrades, state: latest}
    - {name: vagrant, state: latest}
    - {name: xautolock, state: latest}
    - {name: xbacklight, state: latest}
    - {name: xclip, state: latest}
    - {name: xdotool, state: latest}
    - {name: xfce4-clipman, state: latest}
    - {name: xfce4-clipman-plugin, state: latest}
    - {name: xinput, state: latest}
    - {name: xserver-xorg-input-synaptics, state: latest}
    - {name: xserver-xorg-video-intel, state: latest}
    - {name: yamllint, state: latest}
    - {name: zsh, state: latest}

    # Asian font
    - {name: fonts-arphic-ukai, state: latest}
    - {name: fonts-arphic-uming, state: latest}
    - {name: fonts-ipafont-gothic, state: latest}
    - {name: fonts-ipafont-mincho, state: latest}
    - {name: fonts-unfonts-core, state: latest}

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
