---
- name: Install prerequisite packages for installing docker
  apt:
    name: "{{item.name}}"
    state: "{{item.state}}"
  with_items:
    - { name: apt-transport-https, state: present }
    - { name: ca-certificates, state: present }
    - { name: gnupg2, state: present }
    - { name: software-properties-common, state: present }

- name: Add docker official GPG key
  command: sh -c 'curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'

- name: Create /etc/apt/sources.list.d/docker.list
  file:
    path: "{{ item }}"
    state: touch
    owner: root
    mode: 0644
  with_items:
    - /etc/apt/sources.list.d/docker.list

- name: Set up docker repository
  command: sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bulleye stable" | sudo tee /etc/apt/sources.list.d/docker.list'

- name: Install docker
  apt:
    name: "{{item.name}}"
    state: "{{item.state}}"
    update_cache: yes
  with_items:
    - { name: docker-ce, state: present }
    - { name: docker-ce-cli, state: present }
    - { name: containerd.io, state: present }

- name: Add docker group
  become: true
  become_user: root
  group:
    name: docker
    state: present

- name: Add bangn to docker
  become: true
  become_user: root
  user:
    name: bangn
    group: docker
    append: yes
