---

- name: Install prerequisite packages for installing grafana
  apt:
    name: "{{item.name}}"
    state: "{{item.state}}"
    update_cache: yes
  with_items:
    - { name: apt-transport-https, state: present }
    - { name: wget, state: present }
    - { name: software-properties-common, state: present }

- name: Add Grafana official GPG key
  command: sh -c 'wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/grafana.gpg > /dev/null'

- name: Create Grafana repository
  command: sh -c 'echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | sudo tee /etc/apt/sources.list.d/grafana.list'

- name: Install Grafana
  apt:
    name: "{{item.name}}"
    state: "{{item.state}}"
    update_cache: yes
  with_items:
    - { name: grafana, state: present }
