---

- name: "Install deb packages"
  become: yes
  become_method: sudo
  import_tasks: deb_packages.yml

- name: "Install docker"
  become: yes
  become_method: sudo
  import_tasks: docker.yml

- name: "Install packages using curl"
  become: yes
  become_user: bangn
  import_tasks: curl_packages.yml
