---

- name: "Install deb packages"
  become: yes
  become_method: sudo
  import_tasks: deb_packages.yml
  tags: deb_packages

- name: "Install docker"
  become: yes
  become_method: sudo
  import_tasks: docker.yml
  tags: docker

- name: "Install packages using curl"
  become: yes
  become_user: bangn
  import_tasks: curl_packages.yml
  tags: curl_packages
