---
- name: "Install deb packages"
  become: yes
  become_method: sudo
  import_tasks: deb_packages.yml
  tags: deb_packages

- name: "Install docker"
  become: yes
  become_method: sudo
  import_tasks: docker.yml
  tags: docker

- name: "Install Hack Nerd Font"
  become: no
  ansible.builtin.shell: |
    curl -OL "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hack.zip"
    mkdir -p "$HOME/.fonts"
    unzip Hack.zip -d "$HOME/.fonts/Hack/"
    fc-cache -fv
    rm Hack.zip
  tags: font

- name: "Install borgbackup"
  become: yes
  become_method: sudo
  import_tasks: borgbackup.yml
  tags: borgbackup
