---

- name: "Install deb packages"
  become: yes
  become_method: sudo
  import_tasks: deb_packages.yml
  tags: deb_packages

- name: Add apticron config
  become: true
  become_user: root
  template:
    src: etc/apticron/apticron.conf
    dest: /etc/apticron/apticron.conf
    owner: root
    group: root
    mode:  0644
  tags: apt_config

- name: "Install docker"
  become: yes
  become_method: sudo
  import_tasks: docker.yml
  tags: docker

- name: "Install grafana"
  become: yes
  become_method: sudo
  import_tasks: grafana.yml
  tags: grafana

- name: "Install packages using curl"
  become: yes
  become_user: bangn
  import_tasks: curl_packages.yml
  tags: curl_packages
