---

# Updates package from stable only
- name: Add local apt config
  become: true
  become_user: root
  template:
    src:   etc/apt/apt.conf.d/local
    dest:  /etc/apt/apt.conf.d/local
    owner: root
    group: root
    mode:  0644

- name: Add apt config to update packages periodically
  become: true
  become_user: root
  template:
    src:   etc/apt/apt.conf.d/periodic
    dest:  /etc/apt/apt.conf.d/periodic
    owner: root
    group: root
    mode:  0644

- name: Pin stable repos
  become: true
  become_user: root
  template:
    src:   etc/apt/preferences.d/99pin-stable
    dest:  /etc/apt/preferences.d/99pin-stable
    owner: root
    group: root
    mode:  0644

- name: Pin unstable repos
  become: true
  become_user: root
  template:
    src:   etc/apt/preferences.d/99pin-unstable
    dest:  /etc/apt/preferences.d/99pin-unstable
    owner: root
    group: root
    mode:  0644

- name: Add debian buster non-free contrib
  apt_repository:
    repo: deb http://deb.debian.org/debian/ buster contrib non-free
    state: present

- name: Add debian buster security update apt repo
  apt_repository:
    repo: deb http://security.debian.org/ buster/updates contrib non-free
    state: present

- name: Add debian buster stable update apt repo
  apt_repository:
    repo: deb http://ftp.debian.org/debian buster-updates contrib non-free
    state: present

- name: Add debian buster backport apt repo
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main contrib non-free
    state: present

- name: Add debian unstable
  apt_repository:
    repo: deb http://deb.debian.org/debian/ unstable main contrib non-free
    state: present

# Google Chrome
- name: Add google-chrome key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: Add google-chrome repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present

# Postgres
- name: Add posgres key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Add postgres repository
  apt_repository:
    repo: deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main
    state: present

# gcloud
- name: gcloud key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: gcloud repository
  apt_repository:
    repo: deb https://packages.cloud.google.com/apt cloud-sdk main
    state: present
