---
- name: Add local apt config
  become: true
  become_user: root
  template:
    src: etc/apt/apt.conf.d/local
    dest: /etc/apt/apt.conf.d/local
    owner: root
    group: root
    mode: 0644
  tags: apt_config

- name: Add apt config to update packages periodically
  become: true
  become_user: root
  template:
    src: etc/apt/apt.conf.d/51unattended-upgrades
    dest: /etc/apt/apt.conf.d/51unattended-upgrades
    owner: root
    group: root
    mode: 0644
  tags: apt_config

- name: Use debian testing apt repo
  apt_repository:
    repo: deb http://deb.debian.org/debian testing main contrib non-free
    state: present

- name: Configure debian unstable
  apt_repository:
    repo: deb http://deb.debian.org/debian unstable main contrib non-free
    state: absent

- name: Pin unstable repos
  become: true
  become_user: root
  template:
    src: etc/apt/preferences.d/99pin-unstable
    dest: /etc/apt/preferences.d/99pin-unstable
    owner: root
    group: root
    mode: 0644
