---

- name: Clone dotfiles
  git:
    repo: 'https://github.com/bangn/dotfiles'
    dest: /home/bangn/dotfiles
    update: no
  become: yes
  become_user: bangn

- name: Remove default asdfrc
  file:
    path: '/home/bangn/.asdfrc'
    state: absent

- name: Remove default tool-versions
  file:
    path: '/home/bangn/.tool-versions'
    state: absent

- name: Create bakup directory in .vim
  file:
    path: /home/bangn/.vim/bakup
    state: directory
    owner: bangn

- name: Create screenshots directory
  become: yes
  become_user: bangn
  file:
    path: /home/bangn/Pictures/screenshots
    state: directory
    owner: bangn
