---
- name: Clone dotfiles
  git:
    repo: "https://github.com/bangn/dotfiles"
    dest: "{{ ansible_env.HOME }}/dotfiles"
    update: no
  become: yes
  become_user: "{{ usename }}"

- name: Create screenshots directory
  become: yes
  become_user: "{{ usename }}"
  file:
    path: "{{ ansible_env.HOME }}/Pictures/screenshots"
    state: directory
    owner: "{{ usename }}"
