---
- name: Clone dotfiles
  git:
    repo: "https://github.com/bangn/dotfiles"
    dest: /home/bangn/dotfiles
    update: no
  become: yes
  become_user: bangn

- name: Create screenshots directory
  become: yes
  become_user: bangn
  file:
    path: /home/bangn/Pictures/screenshots
    state: directory
    owner: bangn
