---

- name: Create /etc/X11/xorg.conf.d/20-intel.conf file if it is not exist
  file:
    path: "{{ item }}"
    state: touch
    owner: root
    mode: 0755
  with_items:
    - /etc/X11/xorg.conf.d/20-intel.conf

- name: Tweak intel backlight
  blockinfile:
    path: /etc/X11/xorg.conf.d/20-intel.conf
    backup: yes
    block: |
      Section "Device"
              Identifier  "card0"
              Driver      "intel"
              Option      "Backlight"  "intel_backlight"
              BusID       "PCI:0:2:0"
      EndSection
