---

- name: Install lxc deb packages
  apt:
    name: "{{item.name}}"
    state: "{{item.state}}"
    update_cache: yes
  with_items:
    - {name: libvirt-clients, state: latest}
    - {name: libvirt-daemon-system, state: latest}
    - {name: iptables, state: latest}
    - {name: ebtables, state: latest}
    - {name: libxml2-utils, state: latest}
    - {name: iproute2, state: latest}

- name: Add lxc default.conf
  template:
    src:   etc/lxc/default.conf
    dest:  /etc/lxc/default.conf
    owner: root
    group: root
    mode:  0644

- name: virsh net-start default
  command: bash -c 'virsh net-start default'

- name: virsh net-autostart default
  command: bash -c 'virsh net-autostart default'
